# Simulating Coin Flips

In [1]:
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline

In [15]:
# outcome of one coin flip
np.random.randint(2)

1

In [11]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)

array([1, 0, 1, ..., 1, 0, 1])

In [12]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.4985

In [20]:
# outcome of one coin flip
np.random.choice([0, 1])

0

In [21]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([0, 1, 0, ..., 1, 1, 0])

In [22]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.50770000000000004

In [23]:
# outcomes of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([0, 0, 0, ..., 0, 0, 0])

In [9]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.19989999999999999