### Bootstrap Sampling

Below is an array of the possible values you can obtain from a die.  Let's consider different methods of sampling from these values.

In [15]:
import numpy as np
np.random.seed(42)

die_vals = np.array([1,2,3,4,5,6])
die_vals

array([1, 2, 3, 4, 5, 6])

1. Take a random sample of 20 values from **die_vals** using the code below, then answer the question in the first quiz below.

In [16]:
xy = np.random.choice(die_vals, size=20)
xy

array([4, 5, 3, 5, 5, 2, 3, 3, 3, 5, 4, 3, 6, 5, 2, 4, 6, 6, 2, 4])

In [17]:
set(xy)

{2, 3, 4, 5, 6}

`2.` Use the code below to choose another sample from **die_vals**, then answer the question in the first quiz below.

In [10]:
ab = np.random.choice(die_vals, replace=False, size=len(die_vals))
ab

array([1, 2, 6, 3, 5, 4])

> NB: Note the value error when the size of the non-bootstrapped replace = False was 20 

```ValueError  Traceback (most recent call last)
<ipython-input-5-c7c530506a30> in <module>()
----> 1 ab = np.random.choice(die_vals, replace=False, size=20)
      2 ab
mtrand.pyx in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:18113)()
ValueError: Cannot take a larger sample than population when 'replace=False'```